### ISSUE TITLE
tlsdate-0.0.13 fails to compile with libressl-2.5.0

### ISSUE THREAD

**Issue by zetok** [ioerror/tlsdate#192]
```
src/tlsdate-helper.c: In function ‘run_ssl’:
src/tlsdate-helper.c:1139:5: warning: implicit declaration of function ‘SSLv3_client_method’ [-Wimplicit-function-declaration]
     ctx = SSL_CTX_new(SSLv3_client_method());
     ^
src/tlsdate-helper.c:1139:23: warning: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast
     ctx = SSL_CTX_new(SSLv3_client_method());
                       ^
In file included from ./src/tlsdate-helper.h:38:0,
                 from src/tlsdate-helper.c:78:
/usr/include/openssl/ssl.h:1520:10: note: expected ‘const struct SSL_METHOD *’ but argument is of type ‘int’
 SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
          ^
```

**Comment by quickhot** [comment]
using 1.0
